name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This pull request has been open 6 months with no activity. It will be closed in 30 days unless new commits or comments are added.'
        stale-pr-label: 'stale'
        close-pr-message: 'Closing this pull request.'
        days-before-stale: 5
        days-before-close: 1
        exempt-pr-labels: 'keep-open'
